### ISSUE TITLE
When I tring to unpack a encrypted, it gets error

### ISSUE THREAD

**Issue by iamapig120** [askeladdk/ccmixar#1]
Error info: crypto/blowfish: invalid key size 79
Rename locked.mix.zip as locked.mix to test
And this is the cmd

.\ccmixar.exe unpack -game ra2 -mix "F:\WorkSpace\Ra2 i18n\ccmixar\test\locked.mix"  -dir "F:\WorkSpace\Ra2 i18n\ccmixar\test\locked"

[locked.mix.zip](https://github.com/askeladdk/ccmixar/files/10417261/locked.mix.zip)

**Comment by askeladdk** [comment]
Yes, that happens sometimes but I couldn't figure out the cause.
